### ISSUE TITLE
autoleveling needs to be moved into signal configuration configuration

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-csharp#105]
auto level needs to know information about the signal in order to do a good autolevel. doing auto level in configure common isn't as effective and may lead to trouble since the signal is not yet configured.

**Comment by mdwhitten** [comment]
@NISystemsEngineering/rfic-systems-r-d and I discussed this today. We came up with the following proposals:

- Remove AutoLevel entirely from the RDLs. Because AutoLevel requires knowledge of when to apply it, and appropriate information (such as the correct autolevel length) we may not wish to support it at all. It would instead be implemented within the examples and in TestStand, but not in any base building blocks.
- Add it to the Configure Signal functions and drop support for SpecAn AutoLevel. Since SpecAn doesn't have a concept of a signal, there's not a clear way to apply this successfully within SpecAn.
    - A related question with this is whether Configure Signal should output the new reference level, or leave it to the calling application to read it out.

Please add any thoughts that you have on these proposals.

**Comment by smooresni** [comment]
Could we add a third option? Customer's typically don't autolevel until right before they take a measurement. Could we introduce an initiate method with an optional auto-level flag?

If not, my preference is to remove it.
